require "active_record"
require "change_tracker/version"
require "change_tracker/app/change_tracker"
require "change_tracker/app/models/change"
require "change_tracker/db/migrate/change_tracker_migration.rb"
